<%	String mm_key = request.getParameter("m_key");
if("waptx".equals(mm_key)){%>
		<a href="http://tx.com.cn?<%=paraStringESC%>">返回天下网</a><br/> 
----------<br/>
<%} else if("gamezero".equals(mm_key)){%>
		<a href="http://wap.gamezero.cn">手游天下</a><br/>
----------<br/>
<%} else if("3gg".equals(mm_key)){%>
		<a href="http://wap.3gg.com">魅媒帝国</a><br/>
----------<br/>
<%} else if("gg2mm".equals(mm_key)){%>
		<a href="http://wap.gg2mm.net">果莓互动</a><br/>
----------<br/>
<%} else if("paojiao".equals(mm_key)){%>
		<a href="http://wap.paojiao.com">泡椒网站</a><br/>
----------<br/>
<%} else if("waps".equals(mm_key)){%>
		<a href="http://wap.waps.cn">wap世纪</a><br/>
----------<br/>
<%} else if("a8wap".equals(mm_key)){%>
		<a href="http://wap.a8wap.com">爱8-手机下载站</a><br/>
----------<br/>
<%} else if("h3sky".equals(mm_key)){%>
		<a href="http://wap.h3sky.cn">H3娱乐空间</a><br/>
----------<br/>
<%--<%} else if("173bl".equals(mm_key)){
		<a href="http://173bl.cn">部落网</a><br/>
----------<br/>--%>
<%} else if("mbook".equals(mm_key)){%>
		<a href="http://wap.mbook.cn">移动书城</a><br/>
----------<br/>
<%} else if("wapsxd".equals(mm_key)||"waps_123".equals(mm_key)||"waps_127".equals(mm_key)){%>
		<a href="http://wap.waps.cn">世纪首页</a><br/>
----------<br/>
<%} else if("uucun".equals(mm_key)||"uucun_158".equals(mm_key)||"uucun_151".equals(mm_key)||"uucun_150".equals(mm_key)||"uucun_149".equals(mm_key)||"uucun_152".equals(mm_key)){%>
		<a href="http://wap.uucun.com">返回悠悠村</a><br/>
----------<br/>
<%} else if("3gg_8".equals(mm_key)){%>
		<a href="http://wap.3gg.cn">魅媒帝国</a><br/>
----------<br/>
<%} else if("byread".equals(mm_key)){%>
		<a href="http://wap.byread.com">返回百阅</a><br/>
----------<br/>
<%} else if("hucn".equals(mm_key)){%>
		<a href="http://wap.hucn.com">小虎在线</a><br/>
----------<br/>
<%} else if("dangle".equals(mm_key)){%>
		<a href="http://tx1.dogstart.com/txmud/tx/index614.jsp?<%=paraStringESC%>">返回当乐网</a><br/>
----------<br/> <%}%>

